services:
  backend:
    image: node:18  
    working_dir: /app  
    volumes:
      - .:/app  
      - /app/node_modules  
    env_file: config.local.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: sh -c "npm install && npm run start:dev" 

  postgres:
    image: postgres:15
    env_file: config.local.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
