version: '3.8'
services:
  backend:
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    env_file: config.local.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: sh -c "npm install && npm run start:dev"
    networks:
      - app-network

  postgres:
    image: postgres:15
    env_file: config.local.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
